# Generated by Django 2.1.3 on 2018-11-12 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.TextField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('d', 'Denied')], default='p', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='event', to='events.Person'),
        ),
    ]
