# Generated by Django 2.1.2 on 2018-11-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='host_grad',
        ),
    ]
