# Generated by Django 2.1.2 on 2018-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_host_grad'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_grad',
            field=models.CharField(default='', max_length=50),
        ),
    ]
