# Generated by Django 2.1.2 on 2018-10-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='events',
            field=models.ManyToManyField(to='events.Person'),
        ),
    ]
