# Generated by Django 2.1.3 on 2018-11-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('d', 'Denied')], max_length=1),
        ),
    ]
