# Generated by Django 2.1.2 on 2018-10-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181030_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='events',
            new_name='attendees',
        ),
    ]
