# Generated by Django 2.1.3 on 2018-11-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20181112_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='class_year',
            field=models.CharField(default='n/a', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approved')], default='p', max_length=1),
        ),
    ]
