# Generated by Django 2.1.2 on 2018-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20181127_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='major',
            field=models.CharField(default='', max_length=50),
        ),
    ]
